import type { Metadata } from 'next';
import { Inter, Roboto } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';
import NavBar from './NavBar';
import AuthProvider from './auth/Provider';
import GoogleAnalyticsScript from './GoogleAnalyticsScript';

const inter = Inter({ subsets: ['latin'] });
const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500'] });

// use local font
const poppins = localFont({
	src: '../public/fonts/poppins-regular-webfont.woff2',
	variable: '--font-poppins'
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			data-theme="winter"
		>
			<GoogleAnalyticsScript />
			<AuthProvider>
				<body className={poppins.variable}>
					<NavBar />
					<main className="p-5">{children}</main>
				</body>
			</AuthProvider>
		</html>
	);
}
